if (FML.isModLoaded("chisel") && chisel_enabled) {
	NEI.hide("chisel:*");
	/* fuuuhuuuuuck it
	NEI.hide("chisel:aluminum_stairs*");
	NEI.hide("chisel:marble*");
	NEI.hide("chisel:limestone*");
	NEI.hide("chisel:*cobblestone");
	NEI.hide("chisel:glass*");
	NEI.hide("chisel:sandstone");
	NEI.hide("chisel:sand_snakestone");
	NEI.hide("chisel:sandstone_scribbles");
	NEI.hide("chisel:*_block");
	NEI.hide("chisel:glowstone");
	NEI.hide("chisel:nether*");
	NEI.hide("chisel:stonebricksmooth");
	NEI.hide("chisel:dirt");
	NEI.hide("chisel:ice*");
	NEI.hide("chisel:*_planks");
	NEI.hide("chisel:obsidian*");
	NEI.hide("chisel:iron_bars");
	NEI.hide("chisel:bookshelf");
	NEI.hide("chisel:mossy_templeblock");
	NEI.hide("chisel:cloud");
	NEI.hide("chisel:stained_glass_*");
	NEI.hide("chisel:leaves");
	NEI.hide("chisel:torch*");
	NEI.hide("chisel:jackolantern*");
	NEI.hide("chisel:brickCustom");
	NEI.hide("chisel:pumpkin*");
	NEI.hide("chisel:arcane");
	NEI.hide("chisel:futura");
	NEI.hide("chisel:chest*");
	NEI.hide("chisel:bronzeblock");
	NEI.hide("chisel:marble_stairs*");
	NEI.hide("chisel:packedice*");
	NEI.hide("chisel:antiBlock*");
	NEI.hide("chisel:iron_bars");
	NEI.hide("chisel:iron_block");
	NEI.hide("chisel:lapis_block");
	NEI.hide("chisel:leaves");
//	NEI.hide("chisel:");
	
	NEI.override("chisel:concrete", [0]);
	NEI.override("chisel:holystone", [0]);
	NEI.override("chisel:lavastone", [0]);
	NEI.override("chisel:fantasyblock", [0]);
	NEI.override("chisel:carpet_block", [0]);
	NEI.override("chisel:carpet", [0]);
	NEI.override("chisel:tyrian", [0]);
	NEI.override("chisel:templeblock", [0]);
	NEI.override("chisel:factoryblock", [0]);
	NEI.override("chisel:paperwall", [0]);
	NEI.override("chisel:woolen_clay", [0]);
	NEI.override("chisel:laboratoryblock", [0]);
	NEI.override("chisel:voidstone", [0]);
	NEI.override("chisel:waterstone", [0]);
	NEI.override("chisel:fantasyblock2", [0]);
	NEI.override("chisel:warningSign", [0]);
	NEI.override("chisel:technical", [0]);
	NEI.override("chisel:hexPlating", [0]);
	NEI.override("chisel:voidstone2", [0]);
	NEI.override("chisel:grimstone", [0]);
	NEI.override("chisel:bone", [0]);
	NEI.override("chisel:scorching", [0]);
	NEI.override("chisel:technical2",[0]);
	NEI.override("chisel:hexLargePlating", [0]);
//	NEI.override("chisel:", [0]);

*/
}