if (FML.isModLoaded("TConstruct") && TConstruct_enabled) {
	NEI.hide("TConstruct:*");
	/* fukkit
	NEI.hide("TConstruct:fluid*");
	NEI.hide("TConstruct:*");
	NEI.hide("TConstruct:Glass*");
	NEI.hide("TConstruct:WoolSlab*");
	NEI.hide("TConstruct:materials*");
	NEI.override("TConstruct:ToolForgeBlock",[0]);
	NEI.override("TConstruct:tool*", [0]);
    NEI.override("TConstruct:binding", [0]);
    NEI.override("TConstruct:scytheBlade", [0]);
	NEI.override("TConstruct:pickaxe", [0]);
	NEI.override("TConstruct:shovel", [0]);
	NEI.override("TConstruct:hatchet", [0]);
	NEI.override("TConstruct:broadsword", [0]);
	NEI.override("TConstruct:longsword", [0]);
	NEI.override("TConstruct:rapier", [0]);
	NEI.override("TConstruct:dagger", [0]);
	NEI.override("TConstruct:cutlass", [0]);
	NEI.override("TConstruct:frypan", [0]);
	NEI.override("TConstruct:battlesign", [0]);
	NEI.override("TConstruct:mattock", [0]);
	NEI.override("TConstruct:chisel", [0]);
	NEI.override("TConstruct:lumberaxe", [0]);
	NEI.override("TConstruct:cleaver", [0]);
	NEI.override("TConstruct:scythe", [0]);
	NEI.override("TConstruct:excavator", [0]);
	NEI.override("TConstruct:hammer", [0]);
	NEI.override("TConstruct:battleaxe", [0]);
	NEI.override("TConstruct:potionLauncher", [0]);
	NEI.override("TConstruct:toolRod", [0]);
	NEI.override("TConstruct:toolShard", [0]);
	NEI.override("TConstruct:pickaxeHead", [0]);
	NEI.override("TConstruct:hatchetHead", [0]);
	NEI.override("TConstruct:shovelHead", [0]);
	NEI.override("TConstruct:binding", [0]);
	NEI.override("TConstruct:toughBinding", [0]);
	NEI.override("TConstruct:toughRod", [0]);
	NEI.override("TConstruct:heavyPlate", [0]);
	NEI.override("TConstruct:swordBlade", [0]);
	NEI.override("TConstruct:wideGuard", [0]);
	NEI.override("TConstruct:handGuard", [0]);
	NEI.override("TConstruct:crossbar", [0]);
	NEI.override("TConstruct:knifeBlade", [0]);
	NEI.override("TConstruct:fullGuard", [0]);
	NEI.override("TConstruct:frypanHead", [0]);
	NEI.override("TConstruct:signHead", [0]);
	NEI.override("TConstruct:chiselHead", [0]);
	NEI.override("TConstruct:scytheBlade", [0]);
	NEI.override("TConstruct:broadAxeHead", [0]);
	NEI.override("TConstruct:excavatorHead", [0]);
	NEI.override("TConstruct:largeSwordBlade", [0]);
	NEI.override("TConstruct:hammerHead", [0]);
	NEI.override("TConstruct:bowstring", [0]);
	NEI.override("TConstruct:arrowhead", [0]);
	NEI.override("TConstruct:fletching", [0]);
	NEI.override("TConstruct:ShurikenPart", [0]);
	NEI.override("TConstruct:CrossbowLimbPart", [0]);
	NEI.override("TConstruct:BowLimbPart", [0]);
	NEI.override("TConstruct:CrossbowLimbPart", [0]);
	NEI.override("TConstruct:CrossbowBodyPart", [0]);
	NEI.override("TConstruct:BoltPart", [0]);
	NEI.override("TConstruct:Shuriken", [0]);
	NEI.override("TConstruct:ThrowingKnife", [0]);
	NEI.override("TConstruct:Javelin", [0]);
	NEI.override("TConstruct:ShortBow", [0]);
	NEI.override("TConstruct:LongBow", [0]);
	NEI.override("TConstruct:Crossbow", [0]);
	NEI.override("TConstruct:ArrowAmmo", [0]);
	NEI.override("TConstruct:BoltAmmo", [0]);
	NEI.override("TConstruct:Pattern", [0]);
	NEI.override("TConstruct:Cast", [0]);
	NEI.override("TConstruct:GlassArrows", [0]);
	NEI.override("TConstruct:buckets", [0]);
	NEI.override("TConstruct:*forge", [0]);
	NEI.override("TConstruct:*brick*", [0]);
	NEI.override("TConstruct:*builder*", [0]);
	*/
}

if (FML.isModLoaded("TSteelworks") && TConstruct_enabled) {
	NEI.hide("TSteelworks:molten*");
	NEI.hide("TSteelworks:liquid*");
	NEI.hide("TSteelworks:ScorchedSlab");
	NEI.hide("TSteelworks:*Steel");
	NEI.override("TSteelworks:Limestone", [0]);
	NEI.override("TSteelworks:Cement", [0]);
	//NEI.override("TSteelworks:");
}